((c++-mode . ((flycheck-clang-include-path . ("/opt/homebrew/Cellar/boost/1.83.0/include"))
              (flycheck-clang-args . ("-I" "/opt/homebrew/Cellar/boost/1.83.0/include" "-lboost_program_options"))
	      (c-file-style . "bsd")
              (c-basic-offset . 4)
              (tab-width . 4)
              (indent-tabs-mode . nil))))
